default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: rails_drill_dev

test:
  <<: *default
  database: rails_drill_test

production:
  <<: *default
  database: rails_drill_production
